apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ethtool-monitor
  namespace: prom-system
spec:
  namespaceSelector:
    matchNames:
      - prom-system
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: ethtool-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ethtool-exporter
  name: ethtool-exporter
  namespace: prom-system
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9417
  selector:
    app: ethtool-exporter
---
# ethtool-exporter: https://github.com/Showmax/prometheus-ethtool-exporter/tree/master
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ethtool-exporter
  namespace: prom-system
  labels:
    app: ethtool-exporter
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: ethtool-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9417'
      labels:
        app: ethtool-exporter
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 0

      containers:
        - name: ethtool-exporter
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: drdivano/ethtool-exporter
          ports:
            - containerPort: 9417
              hostPort: 9417
              name: http

          resources:
            limits:
              cpu: 250m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
      tolerations:
        - effect: NoSchedule
          operator: Exists