---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-proxy-grafana
  namespace: prom-system
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: prom-system-prometheus-grafana
          port: 80
---
apiVersion: v1
data:
  admin-password: a2F5dHUtZ2YtcGFzcwo=
  admin-user: a2F5dHUtZ2YK
  ldap-toml: ""
kind: Secret
metadata:
  name: prom-system-prometheus-grafana
  namespace: prom-system
type: Opaque
