---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-proxy-grafana
  namespace: prom-system
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: prom-system-prometheus-grafana
          port: 80
