---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: flux-system
spec:
  timeout: 15m
  chart:
    spec:
      chart: contour
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 17.0.5
  targetNamespace: contour-system
  releaseName: contour
  values:
    configInline:
      enableExternalNameService: true
      tls:
        fallback-certificate:
          namespace: kaytu-octopus
          name: web-tls
#    envoy:
#      logLevel: debug
#    contour:
#      image:
#        debug: true
#      debug: true
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  interval: 1m0s
