apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://fluent.github.io/helm-charts

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  targetNamespace: kaytu-octopus
  interval: 1m
  timeout: 15m
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      version: 0.47.7
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace