apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: flux-system
spec:
  interval: 10m
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  targetNamespace: keda-system
  releaseName: keda
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
      version: 2.10.2
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      operator:
        enabled: true
        podMonitor:
          enabled: true
      metricServer:
        enabled: true
        podMonitor:
          enabled: true