apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  targetNamespace: prom-system
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 2.9.10
  install:
    createNamespace: false
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      rbac:
        pspEnabled: false
    loki:
      isDefault: false
      grafana:
        rbac:
          pspEnabled: false
      serviceAccount:
        enabled: true

      serviceMonitor:
        enabled: true

      prometheusRule:
        enabled: true
        groups:
          - name: loki-rules
            rules:
              - record: job:loki_request_duration_seconds_bucket:sum_rate
                expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
              - record: job_route:loki_request_duration_seconds_bucket:sum_rate
                expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
    promtail:
      tolerations:
        - operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Secret
metadata:
  name: gf-ds-loki
  namespace: prom-system
  annotations:
    "helm.sh/hook-weight": "999"
  labels:
    grafana_datasource: "1"
stringData:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: loki-kaytu
        type: loki
        access: proxy
        isDefault: false 
        url: http://prom-system-loki.prom-system.svc.cluster.local:3100
        jsonData:
          maxLines: 1000
        editable: false