apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opensearch-operator
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://opensearch-project.github.io/opensearch-k8s-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-operator
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 15m
  chart:
    spec:
      chart: opensearch-operator
      sourceRef:
        kind: HelmRepository
        name: opensearch-operator
        namespace: flux-system
      version: 2.5.1
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3