---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  targetNamespace: sealed-secret
  releaseName: sealed-secrets-controller
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.13.4
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
